version: '3.1'
services:
  app:
    container_name: docker-blog-project
    image: docker-blog-project
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
      image: mydocker
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=My postgresql
        - POSTGRES_USER=postgres
        - POSTGRES_DB=DockerBlog